---
title: "Analysis Phytophthora spp. survey"
author: "Daniel Cerritos"
date: "4/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library}
# install.packages(c("cowplot", "googleway", "ggrepel","ggspatial", "libwgeom", "sf", "rnaturalearth", "rnaturalearthdata", "hagis"))
# devtools::install_github("yutannihilation/ggsflabel")
library(here)
library(tidyverse)
library(sf)
library(maps)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggrepel)
library(cowplot)
library(ggsflabel)
library(hagis)
library(pander)
```

# Import data

```{r data}
# samples collection
soil.samples <- read_csv(here("output", "clean_data", "01_soil-samples-2016-2017_clean-data.csv"))
plant.samples <- read_csv(here("output", "clean_data", "01_plant-samples-2018_clean-data.csv"))
# identification of isolates
isolates.recovered <- read_csv(here("data", "all-isolates-in-data-base.csv"))
# pathotype
sojae <- read_csv(here("output", "clean_data", "01_pathotype-psojae_clean-data.csv"))
sansomeana <- read_csv(here("output", "clean_data", "01_pathotype-psansomeana_clean-data.csv"))
#aggressiveness
dry.weigth <- read_csv(here("output", "clean_data", "01_agg_germination-dry-weigth_clean-data.csv"))
area.length <- read_csv(here("output", "clean_data", "01_agg_length-area_clean-data.csv"))
```

# Sample collection

```{r exp analysis}
# 2016-2017
soil.samples %>%
  group_by(year) %>% 
  count() 
soil.samples$county %>% 
  n_distinct() 

# 2018
plant.samples %>%
  count() 
plant.samples$county %>%
  n_distinct()
```

## Map

I use code from here: 
https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html 
https://www.r-graph-gallery.com/330-bubble-map-with-ggplot2.html

```{r samples map}
soil.samples <- soil.samples %>% 
  select(year, long, lat) %>% 
  filter(!is.na(long))

# convert to sf object
soil.samples <- st_as_sf(soil.samples, coords = c("long", "lat"), 
                   crs = 4326, agr = "constant")

soil.samples$year <- as.factor(soil.samples$year)

# subset county data 
world <- ne_countries(scale = "medium", returnclass = "sf")
states <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
counties <- st_as_sf(map("county", plot = FALSE, fill = TRUE))
counties <- subset(counties, grepl("illinois", counties$ID))

# add plant samples data
counties <- counties %>% 
  separate(ID, into = c("state", "county"), sep = ",")

plant.samples <- plant.samples %>% 
  group_by(county) %>% 
  count() %>% 
  rename(plant_samples = n)

plant.samples$county <- tolower(plant.samples$county)
all_data <- left_join(counties, plant.samples, by = "county")

# map 
ggplot(data = world) +
  geom_sf(data = states, fill = NA) + 
  geom_sf(data = all_data, aes(fill = plant_samples), color = "black") +
  geom_sf(data = soil.samples, aes(shape = year),  size = 2) +
  coord_sf(xlim = c(-92, -87), ylim = c(36.5, 43), expand = FALSE) +
  scale_fill_gradient(high = "#2171b5", low = "#bdd7e7", na.value = "white") +
  theme_map()
```

# Identification of isolates

```{r exp isolates}
isolates.recovered %>% 
  group_by(year, source) %>% 
  count()

isolates.recovered %>% 
  group_by(identification) %>% 
  count() 
```

##  Map

```{r map isolates}
# I added the coordinates manually, change code 
isolates <- isolates.recovered %>% 
  select(county, species) %>%  
  mutate(genus = case_when(
    grepl("Phyto", species) ~ "Phytophthora spp.",
    grepl("Pyth", species) ~"Pythium spp."))

isolates <- isolates %>% 
  filter(!is.na(county)) %>% 
  group_by(county, genus) %>% 
  count()

isolates <- isolates %>%  
  mutate(genus = case_when(
    grepl("Phyto", species) ~ "Phytophthora spp.",
    grepl("Pyth", species) ~"Pythium spp."))

write.csv(isolates, here("output", "isolates-count-genus.csv"))

collection.map <- read_csv(here("output", "isolates-count-genus.csv"))
il_counties <- map_data("county", "illinois")

#counties labels 
phyto.conties <- collection.map %>% 
  filter(genus == "Phytophthora spp.")

ggplot() +
  geom_polygon(data = il_counties, aes(x = long, y = lat, group = group), 
               fill = "white", color = "grey50") +
  geom_point(data = collection.map, aes(x = long, y = lat, size = isolates, 
                                        color = genus)) +
  geom_text_repel(data=phyto.conties, aes(x=long, y=lat, label= county), size=5) +
  coord_map() +
  theme_map() 
```

```{r figure species collected}
isolates.summary <- isolates.recovered %>% 
  select(species) %>%
  group_by(species) %>% 
  count() %>%  
  mutate(genus = case_when(
    grepl("Phyto", species) ~ "Phytophthora spp.",
    grepl("Pyth", species) ~"Pythium spp.")) %>% 
  mutate(percentage = (n/182)*100)

isolates.summary %>% 
  ggplot(aes(x = reorder(species, percentage), y = percentage, fill = genus))+
  geom_col() +
  coord_flip() +
  theme_minimal_hgrid()+
  labs(title = "Isolates recovered between 2016 - 2018 in Illinois", 
       y = "Isolates (%)", 
       x = "Species") +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05)))+
  theme_minimal_hgrid()+
  panel_border() +
  theme(legend.position = "none", 
        panel.grid.major.y = element_line(linetype = "dotted", 
                                          color = "grey80")) +
  scale_fill_manual(values = c("#FF6A6A", "#BEBEBE"))
```

# Pathotype

## Phytophthora sojae

```{r effective Rps}
# two susceptible controls
williams <- sojae %>% 
  filter(differential == "Williams") %>% 
  group_by(isolate_number, isolate_id, isolate_name, county, differential, gene) %>% 
  summarise(dead = sum(dead), 
            total = sum(total))

sojae <- sojae %>% 
  filter(!differential == "Williams")
sojae <- bind_rows(williams, sojae)
sojae <- sojae %>% 
  mutate(percent.susceptible = round((dead/total)*100))

hagis_args <- list(
  x = sojae,
  cutoff = 75,
  control = "rps",
  sample = "isolate_id",
  gene = "gene",
  perc_susc = "percent.susceptible"
)
# effective Rps
Rps.summary <- do.call(summarize_gene, hagis_args)
Rps.summary %>% 
  ggplot(aes(x = gene, y = percent_pathogenic)) +
  geom_col(fill = "#FF7256", alpha = 0.5) +
  theme_minimal_hgrid() +
  labs(x = "Rps gene", y = "Percent pathogenic") +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))) 
```

```{r complexity}
# mean complexity
complexities <- do.call(calculate_complexities, hagis_args)

complexity.percent <- complexities$grouped_complexities %>% 
  mutate(percent = (frequency/21)*100)

complexity.percent$complexity <- as.numeric(complexity.percent$complexity)

complexity.percent %>% 
  ggplot(aes(x = complexity, y = percent)) +
  geom_col(fill = "#6495ED", alpha = 0.5) +
  theme_minimal_hgrid() +
  labs(x = "Complexity", y = "Percent Isolates") +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))) +
  scale_x_continuous(limits = c(1, 12), breaks = 1:12)

pander(summary(complexities))
```

```{r pathotype}
# diversity
do.call(calculate_diversities, hagis_args)
# pathotypes
diversities_table(diversity)
```

## Phytophthora sansomeana

```{r sansomena effective genes}
sansomeana <- sansomeana %>% 
  mutate(percent.susceptible = round((dead/total)*100))

sansomeana.rps <- summarize_gene(
  x = sansomeana,
  cutoff = 75,
  control = "rps",
  sample = "isolate_id",
  gene = "gene",
  perc_susc = "percent.susceptible"
)

sansomeana.rps %>% 
  ggplot(aes(x = gene, y = percent_pathogenic)) +
  geom_col(fill = "#FF7256", alpha = 0.5) +
  theme_minimal_hgrid() +
  labs(x = "Rps gene", y = "Percent pathogenic") +
  scale_y_continuous(
    expand = expansion(mult = c(0, 0.05))) 
```

# Aggressiveness

```{r area and legth}
# root length in experiment 1 was measured by seedling, in 2 and 3 is the total length by pot
area.length <- area.length %>% 
  group_by(experiment, sample) %>% 
  summarise(length_in = mean(length_in), 
            area_in.2 = mean(area_in.2))

area.length <- area.length %>% # change this in data cleaning
  rename(pot = sample)

dry.weigth <- dry.weigth %>% 
  rename(experiment = names)

aggressiveness <- left_join(dry.weigth, area.length, 
                            by = c("experiment", "pot")) 

# results  are by pot, divide by germination to get mean by seedling
aggressiveness <- aggressiveness %>% 
  mutate(shoot.mg = shoot.mg/germination, 
         root.mg = root.mg/germination, 
         length_in = length_in/germination, 
         area_in.2 = area_in.2/germination)
```

## Exploratory plots 

```{r exploratory plots }

# aggressiveness by species
exp_plot <- function(y) {
  ggplot(aggressiveness, aes(x = species, y = .data[[y]], fill = species)) +
    geom_boxplot(alpha = 0.6) +
    geom_point(position = position_jitterdodge()) +
    theme_bw() +
    panel_border() +
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), 
          legend.position = "bottom") +
    facet_grid(~ experiment, scales = "free") +
    labs(x = "species", 
         y = y) 
}

exp_plot("shoot.mg")
exp_plot("root.mg")
exp_plot("length_in")
exp_plot("area_in.2")

# aggressiveness by isolate
exp_plot_2 <- function(y) {
  ggplot(aggressiveness, aes(x = isolate_id, y = .data[[y]], color = species)) + 
    geom_point(alpha = 0.2) +
    geom_jitter(colour="gray50", alpha=0.3, width=0.1) +
    stat_summary(fun.data = "mean_cl_boot", 
                 position = position_dodge(width = 0.5), 
                 alpha = 0.7) +
    theme_bw() +
    theme(axis.text.x=element_text(angle=45, hjust=1)) +
    theme(legend.position = "bottom") +
    facet_grid(experiment ~ ., scales = "free") +
    labs(x = "Isolate ID", 
         y = y) 
}

exp_plot_2("shoot.mg")
exp_plot_2("root.mg")
exp_plot_2("length_in")
exp_plot_2("area_in.2")
```

## Linear models 
